version: '3'
services:
  db:
    image: postgres:13.11
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=unicorns
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  app:
    image: unicorn-store-spring:latest
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/unicorns
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATASOURCE_USERNAME=postgres
    depends_on:
      - db
    ports:
      - "8080:8080"
      - "9990:9990"
