version: '3'
services:
  postgres:
    image: postgres:13.11
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_DB=unicorns
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  wildfly:
    build:
      context: .
    command: /opt/jboss/wildfly/bin/standalone.sh -b 0.0.0.0 -bmanagement 0.0.0.0
    ports:
      - "8080:8080"
      - "8787:8787"
      - "9990:9990"
    depends_on:
      - postgres