server:
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-internal: "true"

  persistentVolume:
    enabled: true
    storageClass: gp3

  files:
    prometheus.yml:
      scrape_configs:
        - job_name: 'ecs-adot-cloudmap'
          scrape_interval: 15s
          dns_sd_configs:
            - names: ['adot.unicornstore.local']
              type: A
              port: 9464

        - job_name: 'k8s-unicorn-pods'
          scrape_interval: 15s
          kubernetes_sd_configs:
            - role: pod
          relabel_configs:
            - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
              action: keep
              regex: true
            - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
              action: replace
              target_label: __metrics_path__
              regex: (.+)
            - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
              separator: ":"
              regex: (.+);(.+)
              target_label: __address__
              replacement: $1:$2
