# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Continuous Integration

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: 'us-east-1'
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: 17
        cache: maven
    - name: Build unicorn-store-spring with Maven
      run: mvn -B clean package --file pom.xml
      working-directory: ./labs/unicorn-store/software/unicorn-store-spring/
    - name: Install AWS CDK
      run: npm install -g aws-cdk
      working-directory: ./labs/unicorn-store/infrastructure/cdk/
    - name: Build CDK db-setup with Maven
      run: mvn -B clean package --file pom.xml
      working-directory: ./labs/unicorn-store/infrastructure/db-setup/
    - name: CDK Synth
      run: cdk synth
      working-directory: ./labs/unicorn-store/infrastructure/cdk/
